name: final_year_project_mobile_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  google_sign_in: ^6.2.2
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  googlemaps_flutter_webservices: ^1.0.2
  google_maps: ^8.1.1
  google_geocoding_api: ^1.5.2
  cloud_firestore: ^5.6.3
  http: ^1.3.0
  flutter_stripe: ^11.4.0
  
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/event_placeholder.jpg
    - assets/images/image1.png
    - assets/images/image.png
    - assets/images/image2.png
    - assets/images/images1.png
    - assets/images/images2.png
    - assets/images/imagem1.png
    - assets/images/imagem2.png
    - assets/images/imaget1.png
    - assets/images/imaget2.png